# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d4f57cad0ac721b4eef80a44eba714d0569b3db385353947d8d4be1397972d32ba81923b2f69d51573716fc68ee3aa41fc9cf2e79fdb4078513b0ef2ff615a2

test:
  secret_key_base: 24893c57ba9a44e4122d84cc0916088b6c15f15e27d159ea8bdd2aa89361aec0ea504024c1b914e0c6f2b19555583f6cf220f196d3cd76356e830deda8c20f61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
